"""Initialize DB

Revision ID: a84a1778030c
Revises: 
Create Date: 2023-05-04 12:16:32.476992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a84a1778030c"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_job_runs_status"), "job_runs", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_job_runs_status"), table_name="job_runs")
    # ### end Alembic commands ###
